Fix "Invalid variable name" error for base of path
If you were aiming for this TAL fragment:

    <p class="error message"
       tal:condition="view/error_message"
       tal:content="structure view/error_message/escapedtext" />

... but instead mistype it as this:

    <p class="error message"
       tal:condition="view/error_message"
       tal:content="structured view/error_message/escapedtext" />

... then you get this very confusing exception:

    zope.tal.taldefs.TALError: Invalid variable name "escapedtext" in
    expression 'structured view/error_message/escapedtext', at ...

But "escapedtext" is not the invalid name here; it's "structured view",
because the typo of "structured" for "structure" means that `zope.tal`
doesn't interpret that part of the attribute before passing it on to
`zope.tales` to evaluate the path expression.  Fix the incorrect error
message.